### ISSUE TITLE
Dynamically query all languages on github

### ISSUE THREAD

**Issue by LordMZTE** [ModProg/language-guesser#1]
Currently, language-guesser is limited to only showing a few hard-coded languages, but it should be possibly to use all languages on github. All the languages github knows are kept in [this yaml file](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml), so we should be able to query it, and then deserialize it. Note that languages with spaces in their names aren't a problem, if the query is delimeted with quotes, for example `language:"language with spaces"`.

I'm interested in contributing :D

**Comment by ModProg** [comment]
probably you could implement a request on the application start to get them

**Comment by ModProg** [comment]
I could see a tokio OnceCell being usefull

**Comment by LordMZTE** [comment]
I think a better approach would be to store them in the github provider's struct. That would avoid any global state, and should even be easier to implement. Should I implement this?

**Comment by ModProg** [comment]
yeah go for it. Just some way to request them on application start once.

The GitHub provider is the right place

**Comment by ModProg** [comment]
You could use serde or parse the yaml directly. If you need any help feel free to ask.
